### ISSUE TITLE
您好，模型下载的链接失效了，请问能再分享一个么

### ISSUE THREAD

**Issue by ZMLQQQ** [ranxi2001/information-extraction-policy-news#1]

**Comment by ranxi2001** [comment]
链接：https://pan.baidu.com/s/1xs_QPz4uHItKGCkbcUGaCw?pwd=zqeb 
提取码：zqeb 
--来自百度网盘超级会员V5的分享

**Comment by ZMLQQQ** [comment]
谢谢您啦，我还想问一下这个train.txt里面一条数据中result_list里面是应该放实体吧，然后prompt是实体所属的类型么，为什么有的一条数据result_list里面什么都没有然后prompt有。方便加一下您的微信么，我的微信是：M18317829770。感谢您对我提供的帮助。





，
***@***.***







                       
Original Email
                       
                     

Sender:"孤飞"< ***@***.*** &gt;;

Sent Time:2024/4/7 20:05

To:"ranxi2001/information-extraction-policy-news"< ***@***.*** &gt;;

Cc recipient:"ZMLQQQ"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [ranxi2001/information-extraction-policy-news] 您好，模型下载的链接失效了，请问能再分享一个么 (Issue #1)




 
链接：https://pan.baidu.com/s/1xs_QPz4uHItKGCkbcUGaCw?pwd=zqeb
 提取码：zqeb
 --来自百度网盘超级会员V5的分享

**Comment by ranxi2001** [comment]
数据格式都是标准的，请查阅[UIE开源模型的仓库readme文档](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/README.md)，此处不再提供相关解答，我近期工作方向为区块链，不再维护AI项目。

**Comment by ranxi2001** [comment]
此敬

**Comment by ZMLQQQ** [comment]
好的好的，谢谢您了！




，
***@***.***







                       
Original Email
                       
                     

Sender:"孤飞"< ***@***.*** &gt;;

Sent Time:2024/4/7 23:11

To:"ranxi2001/information-extraction-policy-news"< ***@***.*** &gt;;

Cc recipient:"ZMLQQQ"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [ranxi2001/information-extraction-policy-news] 您好，模型下载的链接失效了，请问能再分享一个么 (Issue #1)




 
数据格式都是标准的，请查阅UIE开源模型的仓库readme文档，此处不再提供相关解答，我近期工作方向为区块链，不再维护AI项目。
